---
permalink: online-help/concept-port-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: 'La pagina Port/Performance Explorer (Esplora porte/prestazioni) fornisce una panoramica dettagliata delle performance di tutte le porte di un cluster.' 
---
= Pagina Port/Performance Explorer (Esplora porte/prestazioni)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Port/Performance Explorer (Esplora porte/prestazioni) fornisce una panoramica dettagliata delle performance di tutte le porte di un cluster.

[NOTE]
====
I valori dei contatori delle prestazioni vengono visualizzati solo per le porte fisiche. I valori dei contatori non vengono visualizzati per VLAN o gruppi di interfacce.

====
La pagina Port/Performance Explorer (Esplora porte/prestazioni) consente di tenere traccia e confrontare le prestazioni delle porte durante un periodo di tempo specifico, consentendo di risolvere i problemi e ottimizzare le prestazioni delle porte.

Utilizzando la funzionalità di visualizzazione e confronto è possibile confrontare le prestazioni di questa porta con:

* altre porte sullo stesso nodo
* il nodo su cui risiede la porta
* interfacce di rete presenti sulla porta


[NOTE]
====
Quando si effettua il filtraggio utilizzando l'opzione "`network interfaces on this port`" (interfacce di rete su questa porta), vengono visualizzate solo le LIF dei cluster e dei dati. Non vengono visualizzate le LIF di intercluster.

====
La pagina Port/Performance Explorer (Esplora porte/prestazioni) consente di:

* Visualizza i problemi relativi alle soglie e i relativi dettagli
* Tenere traccia e confrontare i dati relativi alle performance delle porte
* Analizzare e risolvere i problemi relativi alla soglia
* Analizzare e risolvere i problemi relativi alle prestazioni

