---
permalink: online-help/concept-managing-reports.html 
sidebar: sidebar 
keywords:  
summary: 'Active IQ Unified Manager consente di creare e gestire report direttamente dall"interfaccia utente di Unified Manager, in modo da visualizzare informazioni sullo stato di salute, la capacità, le performance e la protezione degli oggetti storage nei cluster. La revisione di queste informazioni può aiutarti a identificare i potenziali problemi prima che si verifichino.' 
---
= Gestione dei report
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager consente di creare e gestire report direttamente dall'interfaccia utente di Unified Manager, in modo da visualizzare informazioni sullo stato di salute, la capacità, le performance e la protezione degli oggetti storage nei cluster. La revisione di queste informazioni può aiutarti a identificare i potenziali problemi prima che si verifichino.

È possibile scaricare i report come valori separati da virgola (.csv), Microsoft Excel (.xlsx) o file PDF. È inoltre possibile pianificare l'invio di un report tramite e-mail a un gruppo di destinatari. I report vengono inviati come allegati e-mail.

Oltre a generare report dall'interfaccia utente, è possibile estrarre i dati di stato e performance da Unified Manager utilizzando i seguenti metodi aggiuntivi:

* Utilizzo degli strumenti ODBC (Open Database Connectivity) e ODBC per accedere direttamente al database per ottenere informazioni sul cluster
* Esecuzione delle API REST di Unified Manager per restituire le informazioni che si desidera esaminare


A partire da questa release di Active IQ Unified Manager, i report sono stati migliorati con i seguenti miglioramenti:

* Viene inviato un messaggio di posta elettronica per un report in base alla pianificazione configurata. Anche quando si genera un report on-demand, si riceverà un'e-mail.
* Il nome file del report e i metadati del report includono il nome host da cui è stato generato il report.
+
Anche se qualcuno cambia il nome del file, è comunque possibile identificare il nome host da cui è stato generato il report a causa di questo miglioramento.


