---
permalink: online-help/concept-overriding-management-actions-through-scripts.html 
sidebar: sidebar 
keywords:  
summary: È possibile creare script personalizzati e associarli agli avvisi per eseguire azioni specifiche per eventi specifici, senza optare per le azioni di gestione predefinite disponibili nella pagina delle azioni di gestione o nella dashboard di Unified Manager. 
---
= Eseguire l'override delle azioni di gestione tramite script
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare script personalizzati e associarli agli avvisi per eseguire azioni specifiche per eventi specifici, senza optare per le azioni di gestione predefinite disponibili nella pagina delle azioni di gestione o nella dashboard di Unified Manager.

Se si desidera eseguire azioni specifiche per un tipo di evento e scegliere di non correggerle come parte della funzionalità di azione di gestione fornita da Unified Manager, è possibile configurare uno script personalizzato per l'azione specifica. È quindi possibile associare lo script a un avviso per quel tipo di evento e occuparsi di tali eventi singolarmente. In questo caso, le azioni di gestione non vengono generate per quel tipo di evento specifico nella pagina delle azioni di gestione o nella dashboard di Unified Manager.

Per informazioni sull'aggiunta e il test degli script, vedere xref:concept-managing-scripts.adoc[Gestione degli script].
