---
permalink: online-help/concept-understanding-svm-associations.html 
sidebar: sidebar 
keywords:  
summary: I peer delle macchine virtuali di storage sono mappature da una macchina virtuale di storage di origine a una macchina virtuale di storage di destinazione utilizzate dalle applicazioni partner per la selezione delle risorse e il provisioning di volumi secondari. 
---
= Informazioni sui peer di Storage VM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I peer delle macchine virtuali di storage sono mappature da una macchina virtuale di storage di origine a una macchina virtuale di storage di destinazione utilizzate dalle applicazioni partner per la selezione delle risorse e il provisioning di volumi secondari.

I peer vengono sempre creati tra una VM di storage di origine e una VM di storage di destinazione, indipendentemente dal fatto che la VM di storage di destinazione sia una destinazione secondaria o una destinazione terziaria. Non è possibile utilizzare una VM di storage di destinazione secondaria come origine per creare un peer con una VM di storage di destinazione terziaria.

È possibile eseguire il peer di una VM di storage in tre modi:

* Peer di qualsiasi storage VM
+
È possibile creare un peer tra qualsiasi VM di storage di origine primaria e una o più VM di storage di destinazione. Ciò significa che tutte le VM di storage esistenti che attualmente richiedono protezione, nonché tutte le VM di storage create in futuro, vengono dotate di un peering con la VM di storage di destinazione specificata. Ad esempio, è possibile che venga eseguito il backup di applicazioni provenienti da diverse origini in posizioni diverse su una o più macchine virtuali di storage di destinazione in un'unica posizione.

* Peer di una particolare VM di storage
+
È possibile creare un peer tra una specifica VM di storage di origine e una o più VM di storage di destinazione specifiche. Ad esempio, se si forniscono servizi di storage a molti client i cui dati devono essere separati l'uno dall'altro, è possibile scegliere questa opzione per associare una specifica VM di storage di origine a una specifica VM di storage di destinazione assegnata solo a quel client.

* Peer con una VM di storage esterna
+
È possibile creare un peer tra una VM di storage di origine e un volume flessibile esterno di una VM di storage di destinazione.


