---
permalink: online-help/reference-health-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Health: All aggregates (Salute: Tutti gli aggregati) visualizza informazioni sugli aggregati monitorati e consente di visualizzare e modificare le impostazioni delle soglie.' 
---
= Salute: Vista di tutti gli aggregati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Health: All aggregates (Salute: Tutti gli aggregati) visualizza informazioni sugli aggregati monitorati e consente di visualizzare e modificare le impostazioni delle soglie.

Per impostazione predefinita, gli oggetti nelle pagine di visualizzazione vengono ordinati in base alla criticità degli eventi. Gli oggetti con eventi critici vengono elencati per primi e gli oggetti con eventi di avviso vengono elencati per secondi. Ciò fornisce un'indicazione visiva immediata dei problemi che devono essere risolti. Ogni aggregato nella griglia aggregati dispone di collegamenti a Gestore di sistema di ONTAP. Questo collegamento consente di visualizzare la stessa relazione di protezione in Gestore di sistema di ONTAP.

I controlli nella parte superiore della pagina consentono di selezionare una vista particolare (per lo stato, le prestazioni, la capacità e così via), eseguire ricerche per individuare oggetti specifici, creare e applicare filtri per restringere l'elenco dei dati visualizzati, aggiungere/rimuovere/riordinare le colonne della pagina, ed esportare i dati della pagina in un `.csv`, `.pdf`, o. `.xlsx` file. Dopo aver personalizzato la pagina, è possibile salvare i risultati come vista personalizzata e pianificare un report dei dati da generare e inviare via email a intervalli regolari.

È possibile personalizzare le impostazioni delle soglie di capacità per uno o più aggregati utilizzando il pulsante *Edit Threshold* (Modifica soglia).

Vedere xref:reference-aggregate-health-fields.adoc[Aggregare i campi sanitari] per la descrizione di tutti i campi di questa pagina.
