---
permalink: online-help/reference-capacity-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista capacità: Tutti gli aggregati consente di visualizzare informazioni sulla capacità e sull"utilizzo degli aggregati in tutti i cluster. Queste informazioni consentono di comprendere i possibili rischi di capacità e di visualizzare la capacità configurata, utilizzata e inutilizzata degli aggregati.' 
---
= Capacità: Vista di tutti gli aggregati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista capacità: Tutti gli aggregati consente di visualizzare informazioni sulla capacità e sull'utilizzo degli aggregati in tutti i cluster. Queste informazioni consentono di comprendere i possibili rischi di capacità e di visualizzare la capacità configurata, utilizzata e inutilizzata degli aggregati.

I controlli nella parte superiore della pagina consentono di selezionare una vista particolare (per lo stato, le prestazioni, la capacità e così via), eseguire ricerche per individuare oggetti specifici, creare e applicare filtri per restringere l'elenco dei dati visualizzati, aggiungere/rimuovere/riordinare le colonne della pagina, ed esportare i dati della pagina in un `.csv`, `.pdf`, o. `.xlsx` file. Dopo aver personalizzato la pagina, è possibile salvare i risultati come vista personalizzata e pianificare un report dei dati da generare e inviare via email a intervalli regolari.

Vedere xref:reference-aggregate-capacity-fields.adoc[Aggregare i campi di capacità] per la descrizione di tutti i campi di questa pagina.
