---
permalink: online-help/reference-volume-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Utilizzare questa pagina per visualizzare un elenco degli attributi fisici e logici del volume. Queste informazioni potrebbero essere utili per rispondere alle domande relative alle performance. Il titolo di questa pagina dipende dalla visualizzazione di un volume FlexVol o FlexGroup. 
---
= Pagina Volume/Performance Information (informazioni volume/prestazioni)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare questa pagina per visualizzare un elenco degli attributi fisici e logici del volume. Queste informazioni potrebbero essere utili per rispondere alle domande relative alle performance. Il titolo di questa pagina dipende dalla visualizzazione di un volume FlexVol o FlexGroup.



== Attributi del volume

* *Tipo*
+
Il tipo del volume: Lettura-scrittura (RW) o protezione dati (DP).

* *Stile*
+
Lo stile del volume, FlexVol o FlexGroup.

* *Cluster*
+
Il nome del cluster a cui appartiene questo volume FlexVol o FlexGroup. È possibile fare clic sul nome per visualizzare i dettagli del cluster nella pagina Cluster/Performance Explorer.

* *Aggregati*
+
Il nome dell'aggregato su cui risiede questo volume FlexVol o il numero di aggregati su cui risiede questo volume FlexGroup.

+
Per i volumi FlexVol, è possibile fare clic sul nome per visualizzare i dettagli dell'aggregato nella pagina aggregato/Esplora prestazioni. Per i volumi FlexGroup, è possibile fare clic sul numero per visualizzare gli aggregati utilizzati in questo volume FlexGroup nella pagina prestazioni/inventario aggregati.

* *Storage VM*
+
Il nome della SVM a cui appartiene questo volume FlexVol o FlexGroup. È possibile fare clic sul nome per visualizzare i dettagli SVM nella pagina Storage VM/Performance Explorer.

* *Policy di tiering*
+
Il criterio di tiering impostato sul volume. Il criterio viene applicato solo quando il volume viene distribuito su un aggregato FabricPool. Le policy disponibili sono:

+
** Nessuno. I dati di questo volume rimangono sempre nel Tier di performance.
** Solo Snapshot. Solo i dati Snapshot vengono spostati automaticamente nel Tier cloud. Tutti gli altri dati rimangono nel Tier di performance.
** Backup. Sui volumi di data Protection, tutti i dati utente trasferiti iniziano nel Tier cloud, ma le letture client successive possono causare lo spostamento dei dati hot nel Tier di performance.
** Automatico. I dati su questo volume vengono spostati automaticamente tra il livello di performance e il livello cloud quando ONTAP determina che i dati sono "`hot`" o "`cold`".
** Tutto. I dati di questo volume rimangono sempre nel Tier cloud.


* *Tipo RAID*
+
Il tipo di ridondanza utilizzato nel Tier di performance dell'aggregato in cui risiede questo volume. Tipi possibili:

+
** RAID0
** RAID4
** RAID-DP
** RAID-TEC


+
[NOTE]
====
Il valore "`non applicabile`" viene visualizzato per i volumi FlexGroup perché i volumi costituenti possono trovarsi su aggregati di diversi tipi di RAID.

====
* *Capacità (libera/totale)*
+
Lo storage totale disponibile nel volume, in gigabyte, e la quantità di storage attualmente disponibile.

* *Spazio logico utilizzato*
+
La dimensione reale dei dati memorizzati su questo volume senza applicare i risparmi derivanti dall'utilizzo delle tecnologie di efficienza dello storage ONTAP.


