---
permalink: online-help/reference-capacity-all-qtrees-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Capacity: All Qtree consente di visualizzare informazioni sulla capacità e sull"utilizzo dei qtree in tutti i cluster. Queste informazioni consentono di comprendere i possibili rischi di capacità e di visualizzare la percentuale di dischi configurati e utilizzati e il numero di file.' 
---
= Capacità: Vista di tutti i Qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Capacity: All Qtree consente di visualizzare informazioni sulla capacità e sull'utilizzo dei qtree in tutti i cluster. Queste informazioni consentono di comprendere i possibili rischi di capacità e di visualizzare la percentuale di dischi configurati e utilizzati e il numero di file.

Per impostazione predefinita, gli oggetti nelle pagine di visualizzazione vengono ordinati in base alla criticità degli eventi. Gli oggetti con eventi critici vengono elencati per primi e gli oggetti con eventi di avviso vengono elencati per secondi. Ciò fornisce un'indicazione visiva immediata dei problemi che devono essere risolti.

I controlli nella parte superiore della pagina consentono di selezionare una vista particolare (per lo stato, le prestazioni, la capacità e così via), eseguire ricerche per individuare oggetti specifici, creare e applicare filtri per restringere l'elenco dei dati visualizzati, aggiungere/rimuovere/riordinare le colonne della pagina, ed esportare i dati della pagina in un `.csv`, `.pdf`, o. `.xlsx` file. Dopo aver personalizzato la pagina, è possibile salvare i risultati come vista personalizzata e pianificare un report dei dati da generare e inviare via email a intervalli regolari.

È possibile personalizzare le impostazioni delle soglie di capacità per una o più qtree utilizzando il pulsante *Edit Threshold* (Modifica soglia).

Vedere xref:reference-qtree-capacity-fields.adoc[Campi di capacità del qtree] per la descrizione di tutti i campi di questa pagina.
