---
permalink: online-help/reference-performance-all-nodes-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Performance: All Nodes (prestazioni: Tutti i nodi) visualizza una panoramica degli eventi di performance, dei dati e delle informazioni di configurazione per ciascun nodo monitorato da un"istanza di Unified Manager. In questo modo è possibile monitorare rapidamente le performance dei nodi e risolvere i problemi di performance e gli eventi di soglia.' 
---
= Performance: Vista di tutti i nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Performance: All Nodes (prestazioni: Tutti i nodi) visualizza una panoramica degli eventi di performance, dei dati e delle informazioni di configurazione per ciascun nodo monitorato da un'istanza di Unified Manager. In questo modo è possibile monitorare rapidamente le performance dei nodi e risolvere i problemi di performance e gli eventi di soglia.

Per impostazione predefinita, gli oggetti nelle pagine di visualizzazione vengono ordinati in base alla criticità degli eventi. Gli oggetti con eventi critici vengono elencati per primi e gli oggetti con eventi di avviso vengono elencati per secondi. Ciò fornisce un'indicazione visiva immediata dei problemi che devono essere risolti.

I controlli nella parte superiore della pagina consentono di selezionare una vista particolare (per lo stato, le prestazioni, la capacità e così via), eseguire ricerche per individuare oggetti specifici, creare e applicare filtri per restringere l'elenco dei dati visualizzati, aggiungere/rimuovere/riordinare le colonne della pagina, ed esportare i dati della pagina in un `.csv`, `.pdf`, o. `.xlsx` file. Dopo aver personalizzato la pagina, è possibile salvare i risultati come vista personalizzata e pianificare un report dei dati da generare e inviare via email a intervalli regolari.

Nel menu *Report*, l'opzione *hardware Inventory Report* viene fornita quando Unified Manager e i cluster gestiti vengono installati in un sito senza connettività di rete esterna. Questo pulsante genera un `.csv` file che contiene un elenco completo di informazioni su cluster e nodi, ad esempio numeri di modello e di serie dell'hardware, tipi e conteggi di dischi, licenze installate e altro ancora. Questa funzionalità di reporting è utile per il rinnovo del contratto all'interno di siti sicuri non connessi alla piattaforma NetAppActive IQ.

È possibile assegnare criteri di soglia delle performance a qualsiasi oggetto presente nelle pagine di inventario degli oggetti o cancellare i criteri di soglia utilizzando i pulsanti *Assign Performance Threshold Policy* e *Clear Performance Threshold Policy*.

Vedere xref:reference-node-performance-fields.adoc[Campi relativi alle performance dei nodi] per la descrizione di tutti i campi di questa pagina.
