---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords:  
summary: 'La pagina Dashboard contiene "pannelli" che visualizzano l"elevato livello di capacità, performance e sicurezza dei cluster monitorati. Questa pagina fornisce anche un pannello azioni di gestione che elenca le correzioni che Unified Manager può apportare per risolvere determinati eventi.' 
---
= Pagina del dashboard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nella pagina Dashboard sono presenti "`panels`" che mostrano l'elevato livello di capacità, performance e sicurezza dei cluster monitorati. Questa pagina fornisce anche un pannello azioni di gestione che elenca le correzioni che Unified Manager può apportare per risolvere determinati eventi.

La maggior parte dei pannelli visualizza anche il numero di eventi attivi in tale categoria e il numero di nuovi eventi aggiunti nelle 24 ore precedenti. Queste informazioni consentono di decidere quali cluster è necessario analizzare ulteriormente per risolvere gli eventi. Facendo clic sugli eventi vengono visualizzati gli eventi principali e viene fornito un collegamento alla pagina dell'inventario Gestione eventi filtrata per visualizzare gli eventi attivi in tale categoria.

Nella parte superiore della dashboard è possibile selezionare se visualizzare le informazioni per tutti i cluster monitorati ("`tutti i cluster`") o per un singolo cluster. È possibile iniziare visualizzando lo stato di tutti i cluster e quindi eseguire il drill-down dei singoli cluster quando si desidera visualizzare informazioni dettagliate.

[NOTE]
====
Alcuni dei pannelli elencati di seguito non vengono visualizzati nella pagina in base alla configurazione.

====
* *Pannello azioni di gestione*
+
Unified Manager può diagnosticare accuratamente alcuni problemi e fornire una singola soluzione. Quando disponibili, queste risoluzioni vengono visualizzate in questo pannello con un pulsante *Fix it* o *Fix all*. È possibile risolvere questi problemi immediatamente da Unified Manager invece di dover utilizzare Gestione di sistema di ONTAP o l'interfaccia utente di ONTAP. Per visualizzare tutti i problemi, fare clic su

+
Vedere link:concept-fixing-ontap-issues-directly-from-unified-manager.html["Risoluzione dei problemi di ONTAP direttamente da Unified Manager"] per ulteriori informazioni.

* *Pannello capacità*
+
Durante la visualizzazione di tutti i cluster, questo pannello visualizza la capacità fisica utilizzata (dopo aver applicato il risparmio di efficienza dello storage) e la capacità fisica disponibile (senza includere il potenziale risparmio di efficienza dello storage) per ciascun cluster, il numero di giorni in cui i dischi sono previsti per essere pieni, E il rapporto di riduzione dei dati basato sulle impostazioni di efficienza dello storage ONTAP configurate. Inoltre, elenca la capacità utilizzata per qualsiasi Tier cloud configurato. Facendo clic sul grafico a barre si accede alla pagina di inventario degli aggregati per quel cluster. Facendo clic sul testo "`Days to Full`" (Invia a tutto) viene visualizzato un messaggio che identifica l'aggregato con il numero minimo di giorni di capacità rimanenti; fare clic sul nome dell'aggregato per visualizzare ulteriori dettagli.

+
Durante la visualizzazione di un singolo cluster, questo pannello visualizza la capacità fisica utilizzata e la capacità fisica disponibile per gli aggregati di dati ordinati per ciascun tipo di disco nel Tier locale e per il Tier cloud. Facendo clic sul grafico a barre di un tipo di disco, si accede alla pagina di inventario dei volumi per i volumi che utilizzano quel tipo di disco.

* *Pannello Performance Capacity*
+
Durante la visualizzazione di tutti i cluster, questo pannello visualizza il valore della capacità delle performance per ciascun cluster (media nell'ora precedente) e il numero di giorni fino a quando la capacità delle performance non raggiunge il limite massimo (in base al tasso di crescita giornaliero). Facendo clic sul grafico a barre si accede alla pagina di inventario dei nodi per quel cluster. Si noti che la pagina di inventario dei nodi visualizza la capacità di performance media nelle 72 ore precedenti. Facendo clic sul testo "`Days to Full`" (Invia a tutto) viene visualizzato un messaggio che identifica il nodo con il numero minimo di giorni di capacità delle performance rimanenti; fare clic sul nome del nodo per visualizzare ulteriori dettagli.

+
Durante la visualizzazione di un singolo cluster, questo pannello visualizza i valori relativi alla percentuale di utilizzo della capacità di performance del cluster, agli IOPS totali e al throughput totale (MB/s) e il numero di giorni in cui ciascuna di queste tre metriche deve raggiungere il limite massimo.

* *Pannello workload IOPS*
+
Durante la visualizzazione di un singolo cluster, questo pannello visualizza il numero totale di carichi di lavoro attualmente in esecuzione in un determinato intervallo di IOPS e indica il numero di ciascun tipo di disco quando si sposta il cursore sul grafico.

* *Pannello workload Performance*
+
Questo pannello visualizza il numero totale di carichi di lavoro conformi e non conformi assegnati a ciascuna policy PSL (Performance Service Level). Visualizza anche il numero di workload a cui non è assegnato un PSL. Facendo clic su un grafico a barre si accede ai carichi di lavoro conformi assegnati a tale policy nella pagina carichi di lavoro. Facendo clic sul numero che segue il grafico a barre si passa ai carichi di lavoro conformi e non conformi assegnati a tale policy.

* *Pannello di sicurezza*
+
Durante la visualizzazione di tutti i cluster, questo pannello visualizza il numero di cluster conformi e non conformi, il numero di VM di storage conformi e non conformi e il numero di volumi crittografati e non crittografati. La conformità si basa su http://www.netapp.com/us/media/tr-4569.pdf["Guida al rafforzamento della sicurezza di NetApp per ONTAP 9"]. Fare clic sulla freccia destra nella parte superiore del pannello per visualizzare i dettagli di sicurezza per tutti i cluster nella pagina Security (sicurezza).

+
Durante la visualizzazione di un singolo cluster, questo pannello visualizza se il cluster è conforme o meno, il numero di VM di storage conformi e non conformi e il numero di volumi crittografati e non crittografati. Fare clic sulla freccia destra nella parte superiore del pannello per visualizzare i dettagli di sicurezza del cluster nella pagina Security (sicurezza).

* *Pannello Usage Overview (Panoramica utilizzo)*
+
Durante la visualizzazione di tutti i cluster, è possibile scegliere di visualizzare i cluster in base agli IOPS più elevati, al throughput più elevato (MB/s) o alla capacità fisica più elevata utilizzata.

+
Durante la visualizzazione di un singolo cluster, è possibile scegliere di visualizzare i carichi di lavoro in base agli IOPS più elevati, al throughput più elevato (MB/s) o alla capacità logica più elevata utilizzata.


