---
permalink: online-help/reference-edit-cluster-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 'La finestra di dialogo Edit Cluster (Modifica cluster) consente di modificare le impostazioni di connessione di un cluster esistente, inclusi l"indirizzo IP, la porta e il protocollo.' 
---
= Finestra di dialogo Edit Cluster (Modifica cluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Edit Cluster (Modifica cluster) consente di modificare le impostazioni di connessione di un cluster esistente, inclusi l'indirizzo IP, la porta e il protocollo.

È possibile modificare i seguenti campi:

* *Nome host o Indirizzo IP*
+
Consente di specificare l'FQDN, il nome breve o l'indirizzo IP (IPv4 o IPv6) della LIF di gestione del cluster utilizzata per la connessione al cluster.

* *Nome utente*
+
Consente di specificare un nome utente da utilizzare per accedere al cluster.

* *Password*
+
Consente di specificare una password per il nome utente specificato.

* *Porta*
+
Consente di specificare il numero di porta utilizzato per la connessione al cluster. La porta predefinita è 443 per HTTPS.


