---
permalink: online-help/reference-what-ontap-issues-can-unified-manager-fix.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: 'Questa tabella descrive i problemi di ONTAP che possono essere risolti direttamente dall"interfaccia utente di Unified Manager facendo clic sul pulsante Correggi o Correggi tutto.' 
---
= Quali problemi di ONTAP possono risolvere Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questa tabella descrive i problemi di ONTAP che possono essere risolti direttamente dall'interfaccia utente di Unified Manager facendo clic sul pulsante *Correggi* o *Correggi tutto*.

[cols="3*"]
|===
| Nome e descrizione dell'evento | Azione di gestione | Operazione "`Fix it`" 


 a| 
Spazio del volume pieno

Il volume è quasi esaurito e ha superato la soglia di capacità massima. Questa soglia viene impostata per impostazione predefinita sul 90% delle dimensioni del volume.
 a| 
Attiva la crescita automatica del volume
 a| 
Unified Manager determina che la crescita automatica del volume non è configurata per questo volume, pertanto abilita questa funzione in modo che il volume cresca in capacità quando necessario.



 a| 
Inode pieno

Questo volume ha esaurito gli inode e non può accettare nuovi file.
 a| 
Aumentare il numero di inode sul volume
 a| 
Aumenta il numero di inode sul volume del 2%.



 a| 
Rilevata discrepanza nella policy del livello di storage

Il volume contiene molti dati inattivi e la policy di tiering corrente è impostata su "`snappshot-only`" o "`none`".
 a| 
Abilita il tiering automatico del cloud
 a| 
Poiché il volume risiede già su un FabricPool, il criterio di tiering viene modificato in "`auto`" in modo che i dati inattivi vengano spostati nel livello cloud a costo inferiore.



 a| 
Rilevata mancata corrispondenza livello di storage

Il volume contiene molti dati inattivi, ma non si trova su un livello di storage abilitato al cloud (FabricPool).
 a| 
Modifica del Tier di storage dei volumi`
 a| 
Sposta il volume sul Tier di storage abilitato al cloud e imposta il criterio di tiering su "`auto`" per spostare i dati inattivi nel Tier cloud.



 a| 
Log di audit disattivato

Il registro di controllo non è abilitato per la VM di storage
 a| 
Abilitare la registrazione dell'audit per la VM di storage
 a| 
Attiva la registrazione dell'audit sulla VM di storage.

Tenere presente che la VM di storage deve già avere una posizione del registro di controllo locale o remoto configurata.



 a| 
Banner di accesso disattivato

Il banner di accesso per il cluster deve essere abilitato per aumentare la sicurezza rendendo chiare le restrizioni di accesso.
 a| 
Impostare il banner di accesso per il cluster
 a| 
Imposta il banner di accesso del cluster su "`accesso limitato agli utenti autorizzati`".



 a| 
Banner di accesso disattivato

Il banner di accesso per la VM di storage deve essere abilitato per aumentare la sicurezza rendendo chiare le restrizioni di accesso.
 a| 
Impostare il banner di accesso per la VM di storage
 a| 
Imposta il banner di accesso alla VM dello storage su "`accesso limitato agli utenti autorizzati`".



 a| 
SSH utilizza crittografia non sicura

Le cifre con il suffisso "`-cbc`" sono considerate non sicure.
 a| 
Rimuovere le crittografia non sicure dal cluster
 a| 
Rimuove dal cluster le crittografia non sicure, ad esempio aes192-cbc e aes128-cbc.



 a| 
SSH utilizza crittografia non sicura

Le cifre con il suffisso "`-cbc`" sono considerate non sicure.
 a| 
Rimuovere le crittografia non sicure dalla VM di storage
 a| 
Rimuove le crittografia non sicure, ad esempio aes192-cbc e aes128-cbc, dalla VM di storage.



 a| 
Trasporto HTTPS AutoSupport disattivato

Il protocollo di trasporto utilizzato per inviare messaggi AutoSupport al supporto tecnico deve essere crittografato.
 a| 
Impostare HTTPS come protocollo di trasporto per i messaggi AutoSupport
 a| 
Imposta HTTPS come protocollo di trasporto per i messaggi AutoSupport sul cluster.



 a| 
Soglia di squilibrio del carico del cluster violata

Indica che il carico non è bilanciato tra i nodi nel cluster. Questo evento viene generato quando la varianza della capacità di performance utilizzata è superiore al 30% tra i nodi.
 a| 
Bilanciamento dei carichi di lavoro del cluster
 a| 
Unified Manager identifica il volume migliore da spostare da un nodo all'altro per ridurre lo squilibrio, quindi sposta il volume.



 a| 
Soglia di squilibrio della capacità del cluster violata

Indica che la capacità non è bilanciata tra gli aggregati del cluster. Questo evento viene generato quando la varianza della capacità utilizzata è superiore al 70% tra gli aggregati.
 a| 
Bilanciare la capacità del cluster
 a| 
Unified Manager identifica il volume migliore da spostare da un aggregato all'altro per ridurre lo squilibrio, quindi sposta il volume.



 a| 
Performance Capacity used Threshold violato

Indica che il carico sul nodo potrebbe essere utilizzato in eccesso se non si riduce l'utilizzo di uno o più carichi di lavoro altamente attivi. Questo evento viene generato quando il valore della capacità utilizzata per le performance del nodo supera il 100% per più di 12 ore.
 a| 
Limitare il carico elevato sul nodo
 a| 
Unified Manager identifica il volume con IOPS più elevati e applica una policy di QoS utilizzando i livelli IOPS storici previsti e di picco per ridurre il carico sul nodo.



 a| 
Soglia di avviso evento dinamico violata

Indica che il nodo sta già operando in uno stato di overload a causa del carico eccessivamente elevato di alcuni carichi di lavoro.
 a| 
Ridurre il sovraccarico nel nodo
 a| 
Unified Manager identifica il volume con IOPS più elevati e applica una policy di QoS utilizzando i livelli IOPS storici previsti e di picco per ridurre il carico sul nodo.



 a| 
Non è possibile effettuare il takeover

Il failover è attualmente disattivato, pertanto l'accesso alle risorse del nodo durante un'interruzione o un riavvio andrebbe perso fino a quando il nodo non diventa nuovamente disponibile.
 a| 
Abilitare il failover del nodo
 a| 
Unified Manager invia il comando appropriato per abilitare il failover su tutti i nodi del cluster.



 a| 
L'opzione cf.takeover.on_panic è configurata su OFF

L'opzione nodeshell "`cf.takeover.on_panic`" è impostata su *off*, che potrebbe causare un problema sui sistemi configurati con ha.
 a| 
Abilitare il Takeover in caso di panico
 a| 
Unified Manager invia il comando appropriato al cluster per modificare questa impostazione su *on*.



 a| 
Disattiva l'opzione nodeshell snapmirror.enable

La vecchia opzione "`snapmirror.enable`" del nodeshell è impostata su *on*, che potrebbe causare un problema durante l'avvio dopo l'aggiornamento a ONTAP 9.3 o superiore.
 a| 
Impostare l'opzione snapmirror.enable su Off
 a| 
Unified Manager invia il comando appropriato al cluster per modificare questa impostazione su *Off*.



 a| 
Telnet attivato

Indica un potenziale problema di sicurezza perché Telnet non è sicuro e passa i dati in modo non crittografato.
 a| 
Disattiva Telnet
 a| 
Unified Manager invia il comando appropriato al cluster per disattivare Telnet.

|===