---
permalink: online-help/reference-volume-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 'I seguenti campi sono disponibili nella vista capacità: Tutti i volumi e possono essere utilizzati nelle visualizzazioni personalizzate e nei report.' 
---
= Campi relativi alla capacità del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I seguenti campi sono disponibili nella vista capacità: Tutti i volumi e possono essere utilizzati nelle visualizzazioni personalizzate e nei report.

* *Volume*
+
Il nome del volume.

* *Tasso di crescita giornaliero %*
+
Il tasso di crescita che si verifica ogni 24 ore nel volume.

* *Giorni fino al completo*
+
Il numero stimato di giorni rimanenti prima che il volume raggiunga la capacità massima.

* *Dati disponibili %*
+
La capacità di dati disponibile in un volume in percentuale.

* *Capacità dati disponibile*
+
La capacità di dati disponibile in un volume.

* *Dati utilizzati %*
+
I dati utilizzati in un volume in percentuale.

* *Capacità dati utilizzata*
+
La capacità dei dati utilizzata in un volume.

* *Capacità totale dei dati*
+
Capacità totale dei dati (utilizzata più disponibile) in un volume.

* *Spazio logico utilizzato*
+
Lo spazio logico utilizzato dai dati in questo volume senza applicare i risparmi derivanti dall'utilizzo delle tecnologie di efficienza dello storage ONTAP.

* *Snapshot overflow %*
+
La percentuale dello spazio dati utilizzato dalle copie Snapshot.

* *Riserva Snapshot disponibile %*
+
La quantità di spazio disponibile per le copie Snapshot nel volume in percentuale.

* *Snapshot Reserve Available Capacity (capacità disponibile riserva snapshot)*
+
La quantità di spazio disponibile per le copie Snapshot nel volume.

* *Snapshot Reserve used %*
+
La quantità di spazio utilizzata dalle copie Snapshot nel volume in percentuale.

* *Capacità utilizzata riserva Snapshot*
+
La quantità di spazio utilizzata dalle copie Snapshot nel volume.

* *Capacità totale riserva Snapshot*
+
Visualizza la capacità di copia Snapshot totale nel volume.

* *Capacità di quota impegnata*
+
Lo spazio riservato alle quote nel volume.

* *Quota capacità in eccesso*
+
La quantità di spazio che è possibile utilizzare per le quote prima che il sistema generi l'evento Volume quota Overcommit.

* *Numero totale di nodi*
+
Il numero di inode nel volume.

* *Utilizzo inode %*
+
La percentuale di spazio di inode utilizzata nel volume.

* *Thin provisioning*
+
Se la garanzia di spazio è impostata per il volume selezionato. I valori validi sono Sì e No

* *Garanzia di spazio*
+
Opzione di garanzia dello storage associata al volume.

* *Crescita automatica*
+
Se le dimensioni del volume aumentano automaticamente quando lo spazio è esaurito.

* *Eliminazione automatica Snapshot*
+
Se l'eliminazione automatica delle copie Snapshot è attivata o disattivata.

* *Deduplica*
+
Se la deduplica è attivata o disattivata per il volume.

* *Compressione*
+
Se la compressione è attivata o disattivata per il volume.

* *Stato*
+
Lo stato del volume che si sta esportando.

* *Ruolo di protezione*
+
Il ruolo di protezione impostato per il volume.

* *Tipo SnapLock*
+
Se il volume è un volume SnapLock o non SnapLock.

* *Data di scadenza SnapLock*
+
La data di scadenza del SnapLock.

* *Policy di tiering*
+
Il criterio di tiering impostato per il volume. Valido solo se implementato su aggregati abilitati per FabricPool.

* *Policy di caching*
+
Il criterio di caching associato al volume selezionato.

+
Il criterio fornisce informazioni su come avviene il caching di Flash Pool per il volume. Per ulteriori informazioni sui criteri di caching, vedere la vista Health: All Volumes.

* *Priorità di conservazione della cache*
+
La priorità utilizzata per conservare i pool memorizzati nella cache.

* *Storage VM*
+
Il nome della macchina virtuale di storage (SVM) che contiene il volume.

* *Cluster*
+
Il nome del cluster in cui risiede il volume. È possibile fare clic sul nome del cluster per accedere alla pagina dei dettagli sullo stato di salute del cluster.

* *FQDN cluster*
+
Il nome di dominio completo (FQDN) del cluster.


