---
permalink: online-help/task-viewing-the-health-and-capacity-status-of-all-san-array-clusters.html 
sidebar: sidebar 
keywords: All SAN Array,health and capacity 
summary: È possibile utilizzare le pagine di inventario del cluster per visualizzare lo stato di salute e capacità dei cluster All SAN Array. 
---
= Visualizzazione dello stato di salute e capacità di tutti i cluster di array SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare le pagine di inventario del cluster per visualizzare lo stato di salute e capacità dei cluster All SAN Array.



== Prima di iniziare

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.



== A proposito di questa attività

È possibile visualizzare le informazioni generali per tutti i cluster array SAN nella vista Health: All Clusters (Salute: Tutti i cluster) e Capacity: All Clusters (capacità: Tutti i cluster). Inoltre, è possibile visualizzare i dettagli nella pagina Cluster / Health Details.



== Fasi

. Nel riquadro di spostamento a sinistra, fare clic su *Storage* > *Clusters*.
. Assicurarsi che la colonna "`Personality`" sia visualizzata nella vista *Health: Tutti i cluster* oppure aggiungerla utilizzando il controllo *Show / Hide*.
+
In questa colonna viene visualizzato "`All SAN Array`" (tutti gli array SAN) per tutti i cluster di array SAN.

. Esaminare le informazioni.
. Per visualizzare informazioni sulla capacità dello storage in questi cluster, selezionare la vista *capacità: Tutti i cluster*.
. Per visualizzare informazioni dettagliate sullo stato di salute e sulla capacità dello storage in tali cluster, fare clic sul nome di un cluster All SAN Array.
+
Visualizzare i dettagli nelle schede Health (Stato), Capacity (capacità) e Nodes (nodi) nella pagina Cluster / Health details (Dettagli cluster/salute)


