---
permalink: online-help/task-deleting-svm-associations.html 
sidebar: sidebar 
keywords:  
summary: È possibile eliminare i peer delle macchine virtuali di storage per le applicazioni dei partner per rimuovere la relazione di provisioning secondario tra le macchine virtuali di storage di origine e di destinazione; ad esempio, è possibile farlo quando la macchina virtuale di storage di destinazione è piena e si desidera creare un nuovo peer di protezione delle macchine virtuali di storage. 
---
= Eliminazione dei peer di Storage VM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare i peer delle macchine virtuali di storage per le applicazioni dei partner per rimuovere la relazione di provisioning secondario tra le macchine virtuali di storage di origine e di destinazione; ad esempio, è possibile farlo quando la macchina virtuale di storage di destinazione è piena e si desidera creare un nuovo peer di protezione delle macchine virtuali di storage.



== Prima di iniziare

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.



== A proposito di questa attività

Il pulsante *Delete* (Elimina) viene disattivato fino a quando non viene selezionato almeno un peer di storage VM. La modifica delle associazioni che utilizzano le funzioni di eliminazione e creazione influisce solo sulle future operazioni di provisioning e non sposta i volumi di destinazione esistenti.



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Protection* > *Storage VM Peers*.
. Selezionare almeno un peer di storage VM.
+
Il pulsante *Delete* (Elimina) è attivato.

. Fare clic su *Delete.* (Elimina)
+
Viene visualizzata una finestra di dialogo di avviso.

. Fare clic su *Sì* per continuare.
+
Il peer della VM di storage selezionato viene rimosso dall'elenco.


