---
permalink: online-help/task-viewing-the-volume-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: 'Dalla vista Health: All Volumes (Salute: Tutti i volumi), è possibile monitorare l"inventario dei volumi. La vista Capacity: All Volumes (capacità: Tutti i volumi) consente di visualizzare informazioni sulla capacità e sull"utilizzo dei volumi in un cluster.' 
---
= Visualizzazione dell'elenco e dei dettagli dei volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla vista Health: All Volumes (Salute: Tutti i volumi), è possibile monitorare l'inventario dei volumi. La vista Capacity: All Volumes (capacità: Tutti i volumi) consente di visualizzare informazioni sulla capacità e sull'utilizzo dei volumi in un cluster.



== Prima di iniziare

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.



== A proposito di questa attività

È inoltre possibile utilizzare la pagina dei dettagli relativi a volume/salute per visualizzare informazioni dettagliate sui volumi monitorati, tra cui capacità, efficienza, configurazione e protezione dei volumi. È inoltre possibile visualizzare informazioni sulle periferiche correlate e sugli avvisi correlati per un volume specifico.



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Storage* > *Volumes*.
. Scegliere uno dei seguenti metodi per visualizzare i dettagli del volume:
+
** Per visualizzare informazioni dettagliate sullo stato dei volumi in un cluster, nel menu View (Visualizza), selezionare Health: All Volumes view (Salute: Vista di tutti i volumi).
** Per visualizzare informazioni dettagliate sulla capacità e sull'utilizzo dei volumi in un cluster, nel menu View (Visualizza), selezionare Capacity: All Volumes view (capacità: Vista tutti i volumi).
** Per visualizzare i dettagli completi, fare clic sul nome del volume.
+
È inoltre possibile visualizzare i dettagli completi facendo clic su *View Details* (Visualizza dettagli) nella finestra di dialogo Minimal Details (Dettagli minimi).



. Visualizzare gli oggetti correlati al volume facendo clic su *Visualizza correlati* nella finestra di dialogo Dettagli minimi.

