---
settings:
  name: Active IQ Unified Manager 9.9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager
    url: "/active-iq-unified-manager-99"
    version-number: '9.9'
  - name: Unified Manager
    url: "/active-iq-unified-manager-98"
    version-number: '9.8'
  - name: Unified Manager
    url: "/active-iq-unified-manager-97"
    version-number: '9.7'
  - name: Unified Manager
    url: "/oncommand-unified-manager-95"
    version-number: '9.5'
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di Active IQ Unified Manager 9.9
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - title: Inizia subito
    entries:
    - title: Installazione rapida per VMware vSphere
      url: "/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: release-notes.html
    - title: Installazione rapida per VMware vSphere
      url: qsg-vapp.html
    - title: Installazione rapida per Linux
      url: qsg-linux.html
    - title: Installazione rapida per Windows
      url: qsg-windows.html
  - title: Installare e configurare Unified Manager
    links:
    - title: Installazione e aggiornamento su sistemi VMware vSphere
      url: install-vapp/concept-requirements-for-installing-unified-manager.html
    - title: Installazione e aggiornamento su sistemi Linux
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Installazione e aggiornamento su sistemi Windows
      url: install-windows/concept-requirements-for-installing-unified-manager.html
    - title: Configurare Unified Manager
      url: config/concept-configuring-unified-manager.html
  - title: Monitoraggio delle performance
    links:
    - title: Soglie di performance
      url: performance-checker/concept-managing-performance-thresholds.html
    - title: Performance del cluster
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: Gruppo di criteri QoS
      url: performance-checker/concept-managing-performance-using-qos-policy-group-information.html
  - title: Più risorse
    links:
    - title: Video di Unified Manager
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Blog di Unified Manager
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: Documentazione per la versione più recente di Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
