---
settings:
  name: Active IQ Unified Manager 9.9
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di Active IQ Unified Manager 9.9
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - title: Inizia subito
    entries:
    - title: Installazione rapida per VMware vSphere
      url: "/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Note legali
    url: "/legal-notices.html"
