---
permalink: qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Guida rapida per Unified Manager su piattaforma Linux. 
---
= Istruzioni di avvio rapido per le installazioni Linux
:allow-uri-read: 


[role="lead"]
È possibile scaricare il pacchetto di installazione e installare Unified Manager su una piattaforma fisica o virtuale Red Hat Enterprise Linux o CentOS.



== Requisiti di sistema

* Sistema operativo: Red Hat Enterprise Linux e CentOS versione 7.x e 8.x basati sull'architettura x86_64, installati utilizzando l'ambiente di base "Server with GUI" (Server con GUI) dall'opzione Software Selection (selezione software) del programma di installazione del sistema operativo
* RAM: 12 GB, CPU: 9572 MHz in totale
* Spazio libero su disco: 100 GB di spazio su disco nella directory /opt/netapp/data, 50 GB nella partizione root. Per le directory /opt e /var/log montate separatamente, assicurarsi che /opt disponga di 15 GB, /var/log di 16 GB e /tmp di 10 GB di spazio libero


Per informazioni dettagliate sui requisiti di sistema e sull'installazione del prodotto in un sito protetto, consultare la link:./install-linux/concept-requirements-for-installing-unified-manager.html["Requisiti per l'installazione di Unified Manager"] e a. link:http://mysupport.netapp.com/matrix["Matrice di interoperabilità"].



== Installazione di Active IQ Unified Manager



=== Scaricare il programma di installazione

. Scaricare il `ActiveIQUnifiedManager-<version>.zip` pacchetto di installazione.
. Nella directory in cui è stato scaricato il file di installazione, eseguire:


`# unzip ActiveIQUnifiedManager-<version>.zip`



=== Verificare la configurazione del repository

Le procedure per la configurazione dei repository Red Hat Enterprise Linux o CentOS sono specifiche del sito. È possibile utilizzare `pre_install_check.sh` script incluso nel pacchetto di installazione per verificare la configurazione del sistema operativo. Se il sistema è connesso a Internet, riceverai automaticamente le istruzioni per la configurazione dei repository Red Hat Enterprise Linux o CentOS.

`# sudo ./pre_install_check.sh`



=== Installare Unified Manager

Unified Manager utilizza `yum` utility per installare il software e qualsiasi software dipendente. Poiché esistono immagini diverse di Red Hat Enterprise Linux o CentOS, i pacchetti installati dipendono dal software presente nelle immagini. Il `yum` l'utility determina i pacchetti software dipendenti per l'installazione. Per ulteriori informazioni sui pacchetti software dipendenti, consultare la link:./install-linux/reference-red-hat-and-centos-software-and-installation-requirements.html["Software Linux e requisiti di installazione"].

Per installare Unified Manager, eseguire il seguente comando, come utente root o utilizzando `sudo`, dalla directory in cui è stato decompresso il file di installazione:

`# yum install netapp-um<version>.x86_64.rpm`

oppure

`% sudo yum install netapp-um<version>.x86_64.rpm`

Al termine dell'installazione, vengono visualizzate le informazioni per la connessione all'interfaccia utente Web di Unified Manager. Se non si riesce a connettersi all'interfaccia utente Web, fare riferimento a. `README` file fornito con il software per ulteriori informazioni sulle restrizioni della porta 443.
