---
permalink: health-checker/task-viewing-detailed-security-status-for-clusters-and-svms.html 
sidebar: sidebar 
keywords: cluster security status,SVM security status,volume encryption status 
summary: 'La pagina Security (sicurezza) mostra lo stato di sicurezza di alto livello per tutti i cluster e lo stato di sicurezza dettagliato per i singoli cluster. Lo stato dettagliato del cluster include la conformità del cluster, la conformità SVM e la conformità alla crittografia dei volumi.' 
---
= Visualizzazione dettagliata dello stato di sicurezza per cluster e SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Security (sicurezza) mostra lo stato di sicurezza di alto livello per tutti i cluster e lo stato di sicurezza dettagliato per i singoli cluster. Lo stato dettagliato del cluster include la conformità del cluster, la conformità SVM e la conformità alla crittografia dei volumi.



== Fasi

. Nel riquadro di spostamento di sinistra, fare clic su *Dashboard*.
. A seconda che si desideri visualizzare lo stato di sicurezza per tutti i cluster monitorati o per un singolo cluster, selezionare *tutti i cluster* o selezionare un singolo cluster dal menu a discesa.
. Fare clic sulla freccia destra nel pannello *Security*.
+
La pagina Security (sicurezza) visualizza le seguenti informazioni:

+
** lo stato di sicurezza del cluster (numero di cluster conformi o non conformi)
** Lo stato di sicurezza SVM (numero di SVM conformi o non conformi)
** lo stato di crittografia del volume (numero di volumi crittografati o non crittografati)
** i metodi di autenticazione del cluster utilizzati su ciascun cluster


. Fare riferimento a. http://www.netapp.com/us/media/tr-4569.pdf["Guida al rafforzamento della sicurezza di NetApp per ONTAP 9"] Per istruzioni su come rendere tutti i cluster, le SVM e i volumi conformi alle raccomandazioni di sicurezza NetApp.

