---
permalink: health-checker/task-restoring-a-snapshot-backup.html 
sidebar: sidebar 
keywords: restore,linux 
summary: In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati. È possibile ripristinare il database Snapshot di Unified Manager su un sistema operativo locale o remoto utilizzando la console di manutenzione di Unified Manager. 
---
= Ripristino di un backup Snapshot per Linux e Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati. È possibile ripristinare il database Snapshot di Unified Manager su un sistema operativo locale o remoto utilizzando la console di manutenzione di Unified Manager.



== Prima di iniziare

* È necessario disporre delle credenziali dell'utente root per l'host Linux e dei privilegi amministrativi per il computer host Windows su cui è installato Unified Manager.
* Per accedere alla console di manutenzione del server Unified Manager, è necessario disporre di un ID utente e di una password autorizzati.




== A proposito di questa attività

La funzionalità di ripristino è specifica della piattaforma e della versione. È possibile ripristinare un backup di Unified Manager solo sulla stessa versione di Unified Manager.



== Fasi

. Connettersi all'indirizzo IP o al nome di dominio completo del sistema Unified Manager.


[cols="2*"]
|===
| *Linux* | Shell sicura 


 a| 
*Windows*
 a| 
Power Shell

|===
. Accedere al sistema con il nome utente di manutenzione (umadmin) e la password.
. Immettere il comando `maintenance_console` E premere Invio.
. Nella console di manutenzione *Menu principale*, inserire il numero dell'opzione *Backup Restore*.
. Inserire il numero di *Backup and Restore Using NetApp Snapshot* (Backup e ripristino con NetApp Snapshot*).
+
Se si esegue un ripristino su un nuovo server, dopo aver installato Unified Manager non avviare l'interfaccia utente né configurare cluster, utenti o impostazioni di autenticazione al termine dell'installazione. Inserire il numero per *Configure NetApp Snapshot Backup* e configurare le impostazioni di backup Snapshot come sono state configurate sul sistema originale.

. Inserire il numero di *Restore using NetApp Snapshot* (Ripristina con NetApp Snapshot*).
. Selezionare il file di backup Snapshot che si desidera ripristinare e premere *Invio*.
. Una volta completato il processo di ripristino, accedere all'interfaccia utente di Unified Manager.




== Al termine

Dopo aver ripristinato il backup, se il server Workflow Automation non funziona, attenersi alla seguente procedura:

. Sul server Workflow Automation, modificare l'indirizzo IP del server Unified Manager in modo che punti alla macchina più recente.
. Nel server Unified Manager, reimpostare la password del database se l'acquisizione non riesce nel passaggio 1.

