---
permalink: install-windows/reference-windows-software-and-installation-requirements.html 
sidebar: sidebar 
keywords:  
summary: Per una corretta installazione di Unified Manager su Windows, è necessario assicurarsi che il sistema su cui viene installato Unified Manager soddisfi i requisiti software. 
---
= Software Windows e requisiti di installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Per una corretta installazione di Unified Manager su Windows, è necessario assicurarsi che il sistema su cui viene installato Unified Manager soddisfi i requisiti software.



== Software del sistema operativo

Unified Manager è supportato dal sistema operativo Windows a 64 bit per le seguenti lingue:

* Inglese
* Giapponese
* Cinese semplificato


È possibile installare Unified Manager nelle seguenti edizioni di Windows:

* Microsoft Windows Server 2016 Standard e Datacenter Edition
* Microsoft Windows Server 2019 Standard e Datacenter Edition


Si noti che Windows Server 2012 non è supportato come nelle versioni precedenti. Consultare la matrice di interoperabilità per l'elenco completo e aggiornato delle versioni di Windows supportate.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

Il server deve essere dedicato all'esecuzione di Unified Manager. Sul server non devono essere installate altre applicazioni.



== Software di terze parti

I seguenti pacchetti di terze parti sono forniti in bundle con Unified Manager. Se questi pacchetti di terze parti non sono installati nel sistema, Unified Manager li installa come parte dell'installazione.

* Microsoft Visual C& 43; 43; 2015 Redistributable Package versione 14.26.28720.3
* Microsoft Visual C& 43; 43; Redistributable Packages per Visual Studio 2013 versione 12.0.40660
* MySQL Community Edition versione 8.0.21
+
[NOTE]
====
Il programma di installazione di Unified Manager è stato limitato al supporto solo fino a MySQL Community Edition 8.0.21, a causa di un problema di interoperabilità. Non è possibile aggiornare MySQL a una release superiore alla 8.0.21.

====
* Python 3.6.x
* OpenJDK versione 11.0.9
* p7zip versione 18.05 o successiva


[NOTE]
====
A partire da Unified Manager 9.5, OpenJDK viene fornito nel pacchetto di installazione di Unified Manager e installato automaticamente. Oracle Java non è supportato a partire da Unified Manager 9.5.

====
Se MySQL è preinstallato, devi assicurarti che:

* Sta utilizzando la porta predefinita.
* I database di esempio non sono installati.
* Il nome del servizio è "`MYSQL8`".


Unified Manager viene implementato su un server Web WildFly. WildFly17 viene fornito in bundle e configurato con Unified Manager.

[NOTE]
====
Prima di aggiornare qualsiasi software di terze parti, chiudere un'istanza di Unified Manager in esecuzione. Una volta completata l'installazione del software di terze parti, è possibile riavviare Unified Manager.

====


== Requisiti di installazione

* È necessario installare Microsoft .NET 4.5.2 o versione successiva.
* Il `temp` La directory deve essere configurata con 2 GB di spazio su disco per l'estrazione dei file di installazione. Per verificare se la directory è stata creata, eseguire il seguente comando dall'interfaccia della riga di comando: `echo %temp%`
* È necessario riservare 2 GB di spazio su disco nell'unità Windows per il caching dei file MSI di Unified Manager.
* Il Microsoft Windows Server su cui si desidera installare Unified Manager deve essere configurato con un FQDN (Fully Qualified Domain Name) in modo tale che `ping` Le risposte al nome host e all'FQDN sono riuscite.
* Disattivare il servizio di pubblicazione Web internazionale di Microsoft IIS e assicurarsi che le porte 80 e 443 siano libere.
* Durante l'installazione, assicurarsi che l'impostazione Remote Desktop Session host per "`Windows Installer RDS Compatibility`" (compatibilità RDS di Windows Installer) sia disattivata.
* La porta UDP 514 deve essere libera e non deve essere utilizzata da altri servizi.


[NOTE]
====
Il programma di installazione di Unified Manager configura le seguenti esclusioni in Windows Defender:

* Directory dei dati di Unified Manager
* Directory di installazione di Unified Manager
* Directory dei dati MySQL


Se sul server è installato un altro antivirus, è necessario configurare queste esclusioni manualmente.

====