---
section: config
title: Eseguire attività amministrative e di configurazione
entries:
- title: Configurazione di Active IQ Unified Manager
  url: "/config/concept-configuring-unified-manager.html"
  entries:
  - title: Panoramica della sequenza di configurazione
    url: "/config/concept-overview-of-the-configuration-sequence.html"
  - title: Accesso all'interfaccia utente Web di Unified Manager
    url: "/config/task-accessing-oncommand-unified-manager-web-ui.html"
  - title: Esecuzione della configurazione iniziale dell'interfaccia utente Web di
      Unified Manager
    url: "/config/task-performing-the-initial-setup-of-the-unified-manager-web-ui.html"
  - title: Aggiunta di cluster
    url: "/config/task-adding-clusters.html"
  - title: Configurazione di Unified Manager per l'invio di notifiche di avviso
    url: "/config/task-configuring-unified-manager-to-send-alert-notifications.html"
    entries:
    - title: Configurazione delle impostazioni di notifica degli eventi
      url: "/config/task-configuring-event-notification-settings.html"
    - title: Attivazione dell'autenticazione remota
      url: "/config/task-enabling-remote-authentication.html"
    - title: Disattivazione dei gruppi nidificati dall'autenticazione remota
      url: "/config/task-disabling-nested-groups-from-remote-authentication.html"
    - title: Aggiunta di server di autenticazione
      url: "/config/task-adding-authentication-servers.html"
    - title: Verifica della configurazione dei server di autenticazione
      url: "/config/task-testing-the-configuration-of-authentication-servers-um-6-0.html"
    - title: Aggiunta di utenti
      url: "/config/task-adding-users.html"
    - title: Aggiunta di avvisi
      url: "/config/task-adding-alerts.html"
  - title: Eventi EMS aggiunti automaticamente a Unified Manager
    url: "/config/reference-ems-events-that-are-added-automatically-to-unified-manager.html"
  - title: Iscrizione a eventi EMS ONTAP
    url: "/config/task-subscribing-to-ontap-ems-events.html"
  - title: Gestione delle impostazioni di autenticazione SAML
    url: "/config/concept-managing-saml-authentication-settings-um.html"
    entries:
    - title: Requisiti del provider di identità
      url: "/config/reference-identity-provider-requirements-um.html"
    - title: Attivazione dell'autenticazione SAML
      url: "/config/task-enabling-saml-authentication-um.html"
  - title: Modifica della password utente locale
    url: "/config/task-changing-the-local-user-password.html"
  - title: Impostazione del timeout di inattività della sessione
    url: "/config/task-setting-the-session-inactivity-timeout.html"
  - title: Modifica del nome host di Unified Manager
    url: "/config/concept-changing-the-unified-manager-host-name.html"
    entries:
    - title: Modifica del nome host dell'appliance virtuale Unified Manager
      url: "/config/task-changing-the-unified-manager-host-name-on-vmware.html"
      entries:
      - title: Generazione di un certificato di protezione HTTPS
        url: "/config/task-generating-an-https-security-certificate-ocf.html"
      - title: Riavvio della macchina virtuale di Unified Manager
        url: "/config/task-restarting-the-unified-manager-virtual-machine.html"
    - title: Modifica del nome host di Unified Manager sui sistemi Linux
      url: "/config/task-changing-the-unified-manager-host-name-on-rhel-or-centos.html"
  - title: Attivazione e disattivazione della gestione dello storage basata su policy
    url: "/config/task-enabling-and-disabling-policy-based-storage-management.html"
- title: Configurazione del backup di Unified Manager
  url: "/config/concept-configuring-um-backup.html"
- title: Utilizzando la console di manutenzione
  url: "/config/task-using-the-maintenance-console.html"
  entries:
  - title: Quali funzionalità offre la console di manutenzione
    url: "/config/concept-what-functionality-the-maintenance-console-provides.html"
  - title: Cosa fa l'utente che effettua la manutenzione
    url: "/config/concept-what-the-maintenance-user-does.html"
  - title: Funzionalità diagnostiche per l'utente
    url: "/config/concept-what-the-diagnostic-user-does.html"
  - title: Accesso alla console di manutenzione
    url: "/config/task-accessing-the-maintenance-console.html"
  - title: Accesso alla console di manutenzione mediante la console vSphere VM
    url: "/config/task-accessing-the-maintenance-console-using-vsphere.html"
  - title: Menu della console di manutenzione
    url: "/config/concept-maintenance-console-menu.html"
    entries:
    - title: Menu Network Configuration (Configurazione di rete)
      url: "/config/reference-network-configuration-menu.html"
    - title: Menu Configurazione di sistema
      url: "/config/reference-system-configuration-menu.html"
    - title: Menu Support and Diagnostics (supporto e diagnostica)
      url: "/config/reference-support-and-diagnostics-menu.html"
    - title: Opzioni di menu aggiuntive
      url: "/config/reference-additional-menu-options.html"
  - title: Modifica della password utente per la manutenzione in Windows
    url: "/config/task-changing-the-maintenance-user-password-on-windows.html"
  - title: Modifica della password di umadmin sui sistemi Linux
    url: "/config/task-changing-the-umadmin-password-on-rhel.html"
  - title: Modifica delle porte utilizzate da Unified Manager per i protocolli HTTP
      e HTTPS
    url: "/config/task-changing-the-ports-um-uses-for-http-and-https-protocols.html"
  - title: Aggiunta di interfacce di rete
    url: "/config/task-adding-additional-network-interfaces.html"
  - title: Aggiunta di spazio su disco alla directory del database di Unified Manager
    url: "/config/concept-adding-disk-space-to-the-unified-manager-database-directory.html"
    entries:
    - title: Aggiunta di spazio alla directory dei dati dell'host Linux
      url: "/config/task-adding-space-to-the-data-directory-of-the-unified-manager-red-hat-enterprise-linux-host.html"
    - title: Aggiunta di spazio al disco dati della macchina virtuale VMware
      url: "/config/task-adding-space-to-the-data-disk-of-the-vmware-virtual-machine.html"
    - title: Aggiunta di spazio all'unità logica del server Microsoft Windows
      url: "/config/task-adding-space-to-the-data-disk-of-the-microsoft-windows-server.html"
