---
permalink: config/task-adding-clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: È possibile aggiungere un cluster a Active IQ Unified Manager in modo da poter monitorare il cluster. Ciò include la possibilità di ottenere informazioni sul cluster, come lo stato di salute, la capacità, le performance e la configurazione del cluster, in modo da individuare e risolvere eventuali problemi che potrebbero verificarsi. 
---
= Aggiunta di cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere un cluster a Active IQ Unified Manager in modo da poter monitorare il cluster. Ciò include la possibilità di ottenere informazioni sul cluster, come lo stato di salute, la capacità, le performance e la configurazione del cluster, in modo da individuare e risolvere eventuali problemi che potrebbero verificarsi.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.
* È necessario disporre delle seguenti informazioni:
+
** Nome host o indirizzo IP di gestione del cluster
+
Il nome host è l'FQDN o il nome breve utilizzato da Unified Manager per connettersi al cluster. Il nome host deve essere risolto nell'indirizzo IP di gestione del cluster.

+
L'indirizzo IP di gestione del cluster deve essere la LIF di gestione del cluster della SVM (Administrative Storage Virtual Machine). Se si utilizza una LIF di gestione dei nodi, l'operazione non riesce.

** Il cluster deve eseguire il software ONTAP versione 9.1 o superiore.
** Nome utente e password dell'amministratore di ONTAP
+
Questo account deve avere il ruolo _admin_ con l'accesso dell'applicazione impostato su _ontapi_, _ssh_ e _http_.

** Il numero di porta per la connessione al cluster utilizzando il protocollo HTTPS (generalmente la porta 443).
** Si dispone dei certificati richiesti. Sono necessari due tipi di certificati:
+
*Certificati server*: Utilizzati per la registrazione. Per aggiungere un cluster è necessario un certificato valido. Se il certificato del server scade, è necessario rigenerarlo e riavviare Unified Manager affinché i servizi vengano nuovamente registrati automaticamente. Per informazioni sulla generazione dei certificati, consultare l'articolo della Knowledge base (KB): https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["Come rinnovare un certificato SSL in ONTAP 9"]

+
*Certificati client*: Utilizzati per l'autenticazione. Per aggiungere un cluster è necessario un certificato valido. Non è possibile aggiungere un cluster a Unified Manager con un certificato scaduto e, se il certificato client è già scaduto, è necessario rigenerarlo prima di aggiungere il cluster. Tuttavia, se il certificato scade per un cluster già aggiunto e viene utilizzato da Unified Manager, la messaggistica EMS continua a funzionare con il certificato scaduto. Non è necessario rigenerare il certificato client.



+
[NOTE]
====
È possibile aggiungere cluster protetti da NAT/firewall utilizzando l'indirizzo IP NAT di Unified Manager. Tutti i sistemi di automazione del flusso di lavoro o SnapProtect collegati devono essere protetti da NAT/firewall e le chiamate API SnapProtect devono utilizzare l'indirizzo IP NAT per identificare il cluster.

====
* È necessario disporre di spazio sufficiente sul server Unified Manager. Non è possibile aggiungere un cluster al server quando più del 90% dello spazio nella directory del database è già occupato.




== A proposito di questa attività

Per una configurazione MetroCluster, è necessario aggiungere i cluster locali e remoti e i cluster devono essere configurati correttamente.

È possibile monitorare un singolo cluster mediante due istanze di Unified Manager, a condizione che sia stata configurata una seconda LIF di gestione del cluster sul cluster in modo che ogni istanza di Unified Manager si connetta attraverso una LIF diversa.



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Storage Management* > *Cluster Setup*.
. Nella pagina *Cluster Setup*, fare clic su *Add* (Aggiungi).
. Nella finestra di dialogo *Aggiungi cluster*, specificare i valori richiesti, ad esempio il nome host o l'indirizzo IP del cluster, il nome utente, la password e il numero di porta.
+
È possibile modificare l'indirizzo IP di gestione del cluster da IPv6 a IPv4 o da IPv4 a IPv6. Il nuovo indirizzo IP viene visualizzato nella griglia del cluster e nella pagina di configurazione del cluster al termine del successivo ciclo di monitoraggio.

. Fare clic su *Invia*.
. Nella finestra di dialogo *Authorize host* (autorizza host), fare clic su *View Certificate* (Visualizza certificato) per visualizzare le informazioni sul certificato del cluster.
. Fare clic su *Sì*.
+
Unified Manager controlla il certificato solo quando il cluster viene aggiunto inizialmente. Unified Manager non controlla il certificato per ogni chiamata API a ONTAP.





== Risultati

Una volta individuati tutti gli oggetti di un nuovo cluster (circa 15 minuti), Unified Manager inizia a raccogliere dati storici sulle performance per i 15 giorni precedenti. Queste statistiche vengono raccolte utilizzando la funzionalità di raccolta della continuità dei dati. Questa funzionalità fornisce oltre due settimane di informazioni sulle performance per un cluster subito dopo l'aggiunta. Una volta completato il ciclo di raccolta della continuità dei dati, i dati delle performance del cluster in tempo reale vengono raccolti, per impostazione predefinita, ogni cinque minuti.

[NOTE]
====
Dato che la raccolta di 15 giorni di dati sulle performance richiede un uso intensivo della CPU, si consiglia di eseguire l'aggiunta di nuovi cluster in modo che i sondaggi per la raccolta della continuità dei dati non vengano eseguiti su troppi cluster contemporaneamente. Inoltre, se si riavvia Unified Manager durante il periodo di raccolta della continuità dei dati, la raccolta viene interrotta e vengono visualizzate lacune nei grafici delle performance per il periodo di tempo mancante.

====
[TIP]
====
Se viene visualizzato un messaggio di errore che indica che non è possibile aggiungere il cluster, controllare se gli orologi sui due sistemi non sono sincronizzati e se la data di inizio del certificato HTTPS di Unified Manager è successiva alla data sul cluster. È necessario assicurarsi che gli orologi siano sincronizzati utilizzando NTP o un servizio simile.

====