---
permalink: install-linux/task-downloading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Per installare Unified Manager, è necessario scaricare il file Unified Manager.zip dal NetApp Support Site. 
---
= Download di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario scaricare Unified Manager``.zip`` Dal NetApp Support Site per installare Unified Manager.



== Prima di iniziare

È necessario disporre delle credenziali di accesso per il NetApp Support Site.



== A proposito di questa attività

Scarica lo stesso pacchetto di installazione di Unified Manager per i sistemi Red Hat Enterprise Linux e CentOS.



== Fasi

. Accedere al NetApp Support Site e accedere alla pagina *Download* di Unified Manager: https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Sito di supporto NetApp"]
. Selezionare la versione richiesta di Unified Manager e accettare il contratto di licenza con l'utente finale (EULA).
. Scaricare il file di installazione di Unified Manager per Linux e salvare `.zip` in una directory del sistema di destinazione.
+
[NOTE]
====
Assicurarsi di scaricare la versione corretta del file di installazione per il sistema Red Hat Enterprise Linux. A seconda che sia installato Red Hat Enterprise Linux 7 o 8, assicurarsi di scaricare la versione appropriata di Unified Manager``.zip`` file.

====
. Verificare il checksum per assicurarsi che il software sia stato scaricato correttamente.

